spring.application.name=colegio


#spring.datasource.url=jdbc:postgresql://192.168.1.130:5433/colegio
#spring.datasource.username=postgres
#spring.datasource.password=postgres


spring.datasource.url=jdbc:postgresql://localhost:5432/colegio
spring.datasource.username=eureche
spring.datasource.password=Kinect1593


# Esta propiedad indica cómo manejar las tablas automáticamente
spring.jpa.hibernate.ddl-auto=create